# Generated by Django 5.1.6 on 2026-07-09 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detsis_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('ad', models.CharField(db_index=True, max_length=500)),
                ('ust_idare', models.CharField(blank=True, max_length=500)),
                ('idare_kod', models.CharField(blank=True, db_index=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Kurum (DETSIS)',
                'verbose_name_plural': 'Kurumlar (DETSIS)',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ekap_il_id', models.IntegerField(db_index=True, unique=True)),
                ('plaka', models.IntegerField()),
                ('ad', models.CharField(max_length=100)),
                ('is_big_city', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'İl',
                'verbose_name_plural': 'İller',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yuklenici_adi', models.CharField(blank=True, max_length=500)),
                ('sozlesme_tarih', models.CharField(blank=True, max_length=50)),
                ('sozlesme_bedeli', models.CharField(blank=True, max_length=100)),
                ('sozlesme_bedeli_num', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('en_dusuk_teklif', models.CharField(blank=True, max_length=100)),
                ('en_dusuk_teklif_num', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('en_yuksek_teklif', models.CharField(blank=True, max_length=100)),
                ('en_yuksek_teklif_num', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('yaklasik_maliyet', models.CharField(blank=True, max_length=100)),
                ('yaklasik_maliyet_num', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('fesih_string', models.CharField(blank=True, max_length=255)),
                ('tasfiye_transfer_string', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Sözleşme',
                'verbose_name_plural': 'Sözleşmeler',
            },
        ),
        migrations.CreateModel(
            name='OkasCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(db_index=True, max_length=50, unique=True)),
                ('adi', models.CharField(db_index=True, max_length=500)),
                ('adi_eng', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'OKAS Kodu',
                'verbose_name_plural': 'OKAS Kodları',
                'ordering': ['kod'],
            },
        ),
        migrations.CreateModel(
            name='SyncCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('oldest_date', models.DateTimeField(blank=True, null=True)),
                ('newest_date', models.DateTimeField(blank=True, null=True)),
                ('cursor_skip', models.IntegerField(default=0)),
                ('done', models.BooleanField(default=False)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Senkron İmleci',
                'verbose_name_plural': 'Senkron İmleçleri',
            },
        ),
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(db_index=True, max_length=100)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='running', max_length=20)),
                ('items', models.IntegerField(default=0)),
                ('errors', models.IntegerField(default=0)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Senkron Çalışması',
                'verbose_name_plural': 'Senkron Çalışmaları',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kisim_adi', models.CharField(blank=True, max_length=500)),
                ('en_dusuk_teklif', models.CharField(blank=True, max_length=100)),
                ('en_yuksek_teklif', models.CharField(blank=True, max_length=100)),
                ('yaklasik_maliyet', models.CharField(blank=True, max_length=100)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kisimlar', to='ekap.contract')),
            ],
            options={
                'verbose_name': 'Sözleşme Kısmı',
                'verbose_name_plural': 'Sözleşme Kısımları',
            },
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ekap_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('ikn', models.CharField(db_index=True, max_length=100, unique=True)),
                ('ihale_adi', models.TextField(blank=True)),
                ('idare_adi', models.CharField(blank=True, max_length=500)),
                ('idare_id', models.CharField(blank=True, db_index=True, max_length=50)),
                ('ihale_il_adi', models.CharField(blank=True, max_length=100)),
                ('il_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('ilce_adi', models.CharField(blank=True, max_length=100)),
                ('ihale_tarih_saat', models.CharField(blank=True, max_length=50)),
                ('ihale_tarihi', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ilan_tarihi', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ihale_tip', models.IntegerField(blank=True, db_index=True, null=True)),
                ('ihale_tipi_aciklama', models.CharField(blank=True, max_length=200)),
                ('ihale_usul', models.IntegerField(blank=True, null=True)),
                ('ihale_usul_aciklama', models.CharField(blank=True, max_length=200)),
                ('ihale_durum', models.IntegerField(blank=True, db_index=True, null=True)),
                ('ihale_durum_aciklama', models.CharField(blank=True, max_length=200)),
                ('ihale_kapsam_aciklama', models.CharField(blank=True, max_length=200)),
                ('e_ihale', models.BooleanField(default=False)),
                ('dokuman_sayisi', models.IntegerField(default=0)),
                ('ilan_var_mi', models.BooleanField(default=False)),
                ('isin_yapilacagi_yer', models.TextField(blank=True)),
                ('ihale_yeri', models.TextField(blank=True)),
                ('itirazen_sikayet_basvuru_bedeli', models.CharField(blank=True, max_length=100)),
                ('ust_idare', models.CharField(blank=True, max_length=500)),
                ('idare_telefon', models.CharField(blank=True, max_length=100)),
                ('idare_fax', models.CharField(blank=True, max_length=100)),
                ('iptal_tarihi', models.CharField(blank=True, max_length=50)),
                ('iptal_nedeni', models.TextField(blank=True)),
                ('iptal_madde', models.CharField(blank=True, max_length=200)),
                ('list_synced_at', models.DateTimeField(blank=True, null=True)),
                ('detail_synced_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Bekliyor'), ('ok', 'Tamam'), ('error', 'Hata')], db_index=True, default='pending', max_length=10)),
                ('sync_error', models.TextField(blank=True)),
                ('detail_raw', models.JSONField(blank=True, null=True)),
                ('list_raw', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'İhale',
                'verbose_name_plural': 'İhaleler',
                'ordering': ['-ihale_tarihi'],
                'indexes': [models.Index(fields=['ihale_tip', 'ihale_durum'], name='ekap_tender_ihale_t_84c3de_idx'), models.Index(fields=['-ilan_tarihi'], name='ekap_tender_ilan_ta_09293b_idx')],
            },
        ),
        migrations.CreateModel(
            name='OkasItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodu', models.CharField(blank=True, max_length=50)),
                ('adi', models.CharField(blank=True, max_length=500)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='okas_kalemleri', to='ekap.tender')),
            ],
            options={
                'verbose_name': 'İhale OKAS Kalemi',
                'verbose_name_plural': 'İhale OKAS Kalemleri',
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='tender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sozlesmeler', to='ekap.tender'),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ekap_ilan_id', models.CharField(blank=True, db_index=True, max_length=50)),
                ('ilan_tip', models.IntegerField(blank=True, null=True)),
                ('ilan_tarihi', models.DateTimeField(blank=True, null=True)),
                ('baslik', models.CharField(blank=True, max_length=500)),
                ('veri_html', models.TextField(blank=True)),
                ('istekli_adi', models.CharField(blank=True, max_length=500)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ilanlar', to='ekap.tender')),
            ],
            options={
                'verbose_name': 'İlan',
                'verbose_name_plural': 'İlanlar',
                'ordering': ['-ilan_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='TenderDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiket', models.CharField(max_length=100)),
                ('deger', models.CharField(blank=True, max_length=100)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarihler', to='ekap.tender')),
            ],
            options={
                'verbose_name': 'İhale Tarihi',
                'verbose_name_plural': 'İhale Tarihleri',
            },
        ),
    ]
