# Generated by Django 5.1.6 on 2026-07-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='ekap_ilan_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='authority',
            name='detsis_id',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='authority',
            name='idare_kod',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='contract',
            name='sozlesme_tarih',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='okascode',
            name='kod',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='okasitem',
            name='kodu',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tender',
            name='ekap_id',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='tender',
            name='idare_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tender',
            name='ihale_tarih_saat',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tender',
            name='iptal_tarihi',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
