# Generated by Django 5.1.6 on 2026-07-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekap', '0002_alter_announcement_ekap_ilan_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='ozellikler',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tender',
            name='yasa_kapsami',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
