# Generated by Django 5.1.6 on 2026-07-31 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekap', '0005_search_norm'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ham_ad', models.CharField(max_length=500)),
                ('ham_ad_norm', models.CharField(max_length=500, unique=True)),
                ('kaynak', models.CharField(choices=[('sozlesme', 'Sözleşme yüklenici adı'), ('kisim', 'Kısım yüklenici adı'), ('ilan', 'Sonuç ilanı istekli adı'), ('manuel', 'Elle')], default='sozlesme', max_length=20)),
                ('ilk_gorulme', models.DateTimeField(auto_now_add=True)),
                ('son_gorulme', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Yüklenici Yazımı',
                'verbose_name_plural': 'Yüklenici Yazımları',
            },
        ),
        migrations.CreateModel(
            name='ContractorMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sira', models.IntegerField(default=0)),
                ('pilot', models.BooleanField(default=False)),
                ('kaynak_metin', models.CharField(blank=True, max_length=500)),
                ('guven', models.CharField(choices=[('yuksek', 'Yüksek'), ('orta', 'Orta'), ('dusuk', 'Düşük')], default='yuksek', max_length=10)),
            ],
            options={
                'verbose_name': 'Ortak Girişim Üyeliği',
                'verbose_name_plural': 'Ortak Girişim Üyelikleri',
            },
        ),
        migrations.AddField(
            model_name='announcement',
            name='ekap_sozlesme_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='contract',
            name='dokuman_indiren_sayisi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='ekap_ilan_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='contract',
            name='ekap_sozlesme_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='contract',
            name='gecerli_teklif_sayisi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='idare_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contract',
            name='ihale_tip',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='il_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='indirim_orani',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='sozlesme_tarihi',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='teklif_sayisi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='tender_yaklasik_maliyet_num',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='yaklasik_maliyet_kaynak',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='contract',
            name='yuklenici_adi_norm',
            field=models.CharField(blank=True, db_index=True, max_length=500),
        ),
        migrations.AddField(
            model_name='contractsection',
            name='ekap_kisim_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='tender',
            name='contractors_synced_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='sonuc_ilani_eksik',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='tender',
            name='yaklasik_maliyet_num',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanonik_ad', models.CharField(db_index=True, max_length=500)),
                ('kanonik_anahtar', models.CharField(max_length=500, unique=True)),
                ('arama_norm', models.CharField(blank=True, db_index=True, max_length=1000)),
                ('kind', models.CharField(choices=[('firma', 'Firma'), ('sahis', 'Şahıs'), ('ortak_girisim', 'Ortak Girişim')], db_index=True, default='firma', max_length=20)),
                ('tuzel_tip', models.CharField(blank=True, max_length=20)),
                ('uyruk', models.CharField(blank=True, max_length=100)),
                ('adres', models.TextField(blank=True)),
                ('il_adi', models.CharField(blank=True, db_index=True, max_length=100)),
                ('il_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('sozlesme_sayisi', models.IntegerField(db_index=True, default=0)),
                ('ihale_sayisi', models.IntegerField(default=0)),
                ('idare_sayisi', models.IntegerField(default=0)),
                ('toplam_sozlesme_bedeli', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('ilk_sozlesme_tarihi', models.DateTimeField(blank=True, null=True)),
                ('son_sozlesme_tarihi', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ortalama_indirim_orani', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('indirim_orani_ornek_sayisi', models.IntegerField(default=0)),
                ('uye_sayisi', models.IntegerField(default=0)),
                ('ortak_girisim_sayisi', models.IntegerField(default=0)),
                ('uyeleri_cozumlendi', models.BooleanField(default=True)),
                ('agrega_guncelleme', models.DateTimeField(blank=True, null=True)),
                ('ilk_gorulme', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Yüklenici',
                'verbose_name_plural': 'Yükleniciler',
                'ordering': ['-sozlesme_sayisi'],
                'indexes': [models.Index(fields=['-sozlesme_sayisi'], name='ekap_contra_sozlesm_f885c9_idx'), models.Index(fields=['-toplam_sozlesme_bedeli'], name='ekap_contra_toplam__32cd17_idx'), models.Index(fields=['kind', '-sozlesme_sayisi'], name='ekap_contra_kind_023cf0_idx'), models.Index(fields=['-son_sozlesme_tarihi'], name='ekap_contra_son_soz_eba3e2_idx')],
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='yuklenici',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sozlesmeler', to='ekap.contractor'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['yuklenici', '-sozlesme_tarihi'], name='ekap_contra_yukleni_276134_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['-sozlesme_tarihi'], name='ekap_contra_sozlesm_309493_idx'),
        ),
        migrations.AddField(
            model_name='contractoralias',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliaslar', to='ekap.contractor'),
        ),
        migrations.AddField(
            model_name='contractormembership',
            name='ortak_girisim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uyelikler', to='ekap.contractor'),
        ),
        migrations.AddField(
            model_name='contractormembership',
            name='uye',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ortakliklar', to='ekap.contractor'),
        ),
        migrations.AddIndex(
            model_name='contractormembership',
            index=models.Index(fields=['uye'], name='ekap_contra_uye_id_37de8b_idx'),
        ),
        migrations.AddConstraint(
            model_name='contractormembership',
            constraint=models.UniqueConstraint(fields=('ortak_girisim', 'uye'), name='uniq_jv_uye'),
        ),
    ]
