"""Rakip alarmı için "sözleşmeyi ilk kez ne zaman gördük" sinyali (indeks YOK — bkz. model)."""
# Generated by Django 5.1.6 on 2026-08-04 11:39

from django.db import migrations, models

from ._pg_ops import lock_timeout


class Migration(migrations.Migration):

    atomic = True   # `SET LOCAL` transaction kapsamlı

    dependencies = [
        ('ekap', '0011_pro_sinyal_kolonlari'),
    ]

    operations = [
        lock_timeout("5s"),
        migrations.AddField(
            model_name='contract',
            name='ilk_gorulme',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
