# Generated by Django 5.1.6 on 2026-08-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekap', '0012_contract_ilk_gorulme'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringTenderSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seri_anahtar', models.CharField(db_index=True, max_length=40)),
                ('idare_id', models.CharField(db_index=True, max_length=255)),
                ('idare_adi', models.CharField(blank=True, max_length=500)),
                ('en_ust_idare_kod', models.CharField(blank=True, db_index=True, max_length=16)),
                ('il_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('okas_ana_kod', models.CharField(blank=True, db_index=True, max_length=16)),
                ('okas_ana_adi', models.CharField(blank=True, max_length=500)),
                ('ihale_tip', models.IntegerField(blank=True, null=True)),
                ('iskelet', models.CharField(blank=True, max_length=300)),
                ('ornek_ihale_adi', models.TextField(blank=True)),
                ('ihale_sayisi', models.IntegerField(default=0)),
                ('ilk_ilan', models.DateTimeField(blank=True, null=True)),
                ('son_ilan', models.DateTimeField(blank=True, null=True)),
                ('son_ekap_id', models.CharField(blank=True, max_length=255)),
                ('periyot_gun', models.IntegerField(blank=True, null=True)),
                ('sapma_gun', models.IntegerField(blank=True, null=True)),
                ('periyot_tip', models.CharField(blank=True, choices=[('yillik', 'Yıllık'), ('6_aylik', '6 Aylık'), ('3_aylik', '3 Aylık'), ('aylik', 'Aylık'), ('duzensiz', 'Düzensiz')], max_length=12)),
                ('guven', models.CharField(blank=True, max_length=10)),
                ('beklenen_ilan_tarihi', models.DateField(blank=True, null=True)),
                ('beklenen_ay', models.CharField(blank=True, max_length=7)),
                ('aktif', models.BooleanField(default=True)),
                ('ortalama_bedel', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('son_bedel', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('ortalama_indirim', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('indirim_ornek', models.IntegerField(default=0)),
                ('guncelleme', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tekrar Eden İhale Serisi',
                'verbose_name_plural': 'Tekrar Eden İhale Serileri',
                'ordering': ['-ihale_sayisi'],
                'indexes': [models.Index(condition=models.Q(('aktif', True)), fields=['beklenen_ilan_tarihi'], name='ekap_seri_beklenen_idx'), models.Index(fields=['idare_id', '-son_ilan'], name='ekap_seri_idare_idx')],
                'constraints': [models.UniqueConstraint(fields=('seri_anahtar', 'idare_id'), name='uniq_recurring_series')],
            },
        ),
    ]
