# Generated by Django 5.1.6 on 2026-08-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekap', '0015_pro_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketYearStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yil', models.IntegerField(unique=True)),
                ('sozlesme_sayisi', models.IntegerField(default=0)),
                ('toplam_bedel', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True)),
                ('indirim_toplam', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('indirim_ornek', models.IntegerField(default=0)),
                ('teklif_toplam', models.BigIntegerField(blank=True, null=True)),
                ('teklif_ornek', models.IntegerField(default=0)),
                ('firma_tekil', models.IntegerField(blank=True, null=True)),
                ('idare_tekil', models.IntegerField(blank=True, null=True)),
                ('guncelleme', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pazar Yıl Özeti',
                'verbose_name_plural': 'Pazar Yıl Özetleri',
                'ordering': ['-yil'],
            },
        ),
        migrations.CreateModel(
            name='MarketStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yil', models.IntegerField(db_index=True)),
                ('okas_bucket', models.CharField(blank=True, max_length=4)),
                ('ad', models.CharField(blank=True, max_length=500)),
                ('sozlesme_sayisi', models.IntegerField(default=0)),
                ('toplam_bedel', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True)),
                ('indirim_toplam', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('indirim_ornek', models.IntegerField(default=0)),
                ('teklif_toplam', models.BigIntegerField(blank=True, null=True)),
                ('teklif_ornek', models.IntegerField(default=0)),
                ('guncelleme', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pazar İstatistiği',
                'verbose_name_plural': 'Pazar İstatistikleri',
                'ordering': ['-yil', '-toplam_bedel'],
                'indexes': [models.Index(fields=['yil', '-toplam_bedel'], name='ekap_market_yil_bedel_idx'), models.Index(fields=['okas_bucket', 'yil'], name='ekap_market_bucket_yil_idx')],
                'constraints': [models.UniqueConstraint(fields=('yil', 'okas_bucket'), name='ekap_marketstat_uq')],
            },
        ),
    ]
