# Generated by Django 5.1.6 on 2026-08-28 12:23

"""
`Contract.sektor` ingest-kopyası — benchmark'ın sektör kademesi için.

⚠️ Kopya burada DOĞRU tercihtir çünkü `sektor` TEK DEĞERLİdir (~36 kardinalite),
0014'teki `okas_bucket` ile aynı şekil. Keyword'ler çok-değerli olduğu için onlara
aynı şey yapılamaz (6M satırlık ikinci bir M2M olurdu) — benchmark'ın keyword kademesi
bu yüzden iki fazlı çalışır.

⚠️ İndeks burada YOK: kolon önce doldurulur (`sync_contractors` süpürmesi zaten her
sözleşmeye dokunuyor ve `_CONTRACT_FIELDS` üzerinden yazar), indeks sonra 0022'de
CONCURRENTLY kurulur. Ters sırada indeks doldurma sırasında şişerdi.
"""

from django.db import migrations, models

from ._pg_ops import lock_timeout


class Migration(migrations.Migration):

    dependencies = [
        ('ekap', '0020_keyword_models'),
    ]

    operations = [
        lock_timeout("5s"),
        migrations.AddField(
            model_name='contract',
            name='sektor',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
