# Generated by Django 5.1.6 on 2026-09-23 17:28

"""
`TenderNamePattern.uzlasi_eklenen` — ad uzlaşısı onarımının provenans izi.

⚠️ **DB SEVİYESİNDE DEFAULT ŞART** (bkz. `0023_keyword_column_defaults`): Django'nun
`AddField`'i default'u yalnızca mevcut satırları doldurmak için kullanıp düşürür.
Deploy sırasında eski koddaki bir worker `TenderNamePattern` satırı yazarsa
(`keywords.uygula` yeni kalıbı `pending` açar) kolonu INSERT'e hiç koymaz ve
NOT NULL ihlali alır — 2026-08-28'de üç gün veri kaybettiren arızanın aynısı.
"""
from django.db import migrations, models

from ._pg_ops import PgRunSQL


class Migration(migrations.Migration):

    dependencies = [
        ('ekap', '0027_ilan_tarihi_sira_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='tendernamepattern',
            name='uzlasi_eklenen',
            field=models.JSONField(blank=True, default=list),
        ),
        PgRunSQL(
            "ALTER TABLE ekap_tendernamepattern "
            "ALTER COLUMN uzlasi_eklenen SET DEFAULT '[]'::jsonb;",
            "ALTER TABLE ekap_tendernamepattern "
            "ALTER COLUMN uzlasi_eklenen DROP DEFAULT;",
        ),
    ]
