# Generated by Django 5.1.6 on 2026-07-09 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField(blank=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Uygulama Ayarı',
                'verbose_name_plural': 'Uygulama Ayarları',
            },
        ),
        migrations.CreateModel(
            name='Detsis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detsis_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('ad', models.CharField(db_index=True, max_length=500)),
            ],
            options={
                'verbose_name': 'DETSIS İdare',
                'verbose_name_plural': 'DETSIS İdareler',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('Bekliyor', 'Bekliyor'), ('İşlemde', 'İşlemde'), ('Yanıtlandı', 'Yanıtlandı'), ('Kapandı', 'Kapandı')], default='Bekliyor', max_length=20)),
                ('reply', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Destek Talebi',
                'verbose_name_plural': 'Destek Talepleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
