# Generated by Django 5.1.6 on 2026-07-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_detsis'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maintenance_active', models.BooleanField(default=False, verbose_name='Bakım modu açık')),
                ('maintenance_title', models.CharField(blank=True, default='Bakım Çalışması', max_length=200, verbose_name='Bakım başlığı')),
                ('maintenance_message', models.TextField(blank=True, default='Sistemimizde kısa süreli bir bakım çalışması yapıyoruz. Lütfen birazdan tekrar deneyin.', verbose_name='Bakım mesajı')),
                ('min_ios_version', models.CharField(blank=True, default='', help_text='Örn: 1.2.0 — bu sürümün altındaki iOS cihazlar güncellemeye zorlanır. Boş = kontrol kapalı.', max_length=20, verbose_name='Min. iOS sürümü')),
                ('min_android_version', models.CharField(blank=True, default='', help_text='Örn: 1.2.0 — bu sürümün altındaki Android cihazlar güncellemeye zorlanır. Boş = kontrol kapalı.', max_length=20, verbose_name='Min. Android sürümü')),
                ('ios_store_url', models.URLField(blank=True, default='', verbose_name='App Store bağlantısı')),
                ('android_store_url', models.URLField(blank=True, default='https://play.google.com/store/apps/details?id=com.envisoft.ihaletakip', verbose_name='Google Play bağlantısı')),
                ('update_title', models.CharField(blank=True, default='Güncelleme Gerekli', max_length=200, verbose_name='Güncelleme başlığı')),
                ('update_message', models.TextField(blank=True, default='Uygulamayı kullanmaya devam etmek için lütfen en son sürüme güncelleyin.', verbose_name='Güncelleme mesajı')),
            ],
            options={
                'verbose_name': 'Uygulama Durumu',
                'verbose_name_plural': 'Uygulama Durumu',
            },
        ),
    ]
