# Generated by Django 5.1.6 on 2026-07-09 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('tender', 'İhale'), ('info', 'Bilgi'), ('alarm', 'Alarm')], default='info', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('tender_id', models.CharField(blank=True, max_length=100, null=True)),
                ('tender_title', models.CharField(blank=True, max_length=500, null=True)),
                ('tender_ikn', models.CharField(blank=True, max_length=100, null=True)),
                ('institution', models.CharField(blank=True, max_length=500, null=True)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bildirim',
                'verbose_name_plural': 'Bildirimler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('filters', models.JSONField(default=dict)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('alarm', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_filters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kayıtlı Filtre',
                'verbose_name_plural': 'Kayıtlı Filtreler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_id', models.CharField(db_index=True, max_length=100)),
                ('tender_title', models.CharField(blank=True, max_length=500)),
                ('tender_type', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.CharField(default='ekap', max_length=30)),
                ('added_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favori',
                'verbose_name_plural': 'Favoriler',
                'ordering': ['-added_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'tender_id'), name='uniq_user_favorite')],
            },
        ),
        migrations.CreateModel(
            name='SavedTender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_id', models.CharField(blank=True, max_length=100)),
                ('tender_ikn', models.CharField(db_index=True, max_length=100)),
                ('tender_title', models.CharField(blank=True, max_length=500)),
                ('tender_type', models.CharField(blank=True, max_length=50, null=True)),
                ('tender_status', models.CharField(blank=True, max_length=50, null=True)),
                ('tender_city', models.CharField(blank=True, max_length=100, null=True)),
                ('tender_date', models.CharField(blank=True, max_length=50, null=True)),
                ('institution', models.CharField(blank=True, max_length=500, null=True)),
                ('saved_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_tenders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kayıtlı İhale',
                'verbose_name_plural': 'Kayıtlı İhaleler',
                'ordering': ['-saved_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'tender_ikn'), name='uniq_user_saved_tender')],
            },
        ),
        migrations.CreateModel(
            name='TenderAlarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tender_id', models.CharField(db_index=True, max_length=100)),
                ('tender_ikn', models.CharField(blank=True, max_length=100, null=True)),
                ('tender_title', models.CharField(blank=True, max_length=500)),
                ('institution', models.CharField(blank=True, max_length=500, null=True)),
                ('reminder_day', models.BooleanField(default=False)),
                ('document_change', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'İhale Alarmı',
                'verbose_name_plural': 'İhale Alarmları',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'tender_id'), name='uniq_user_alarm')],
            },
        ),
    ]
