# Generated by Django 5.1.6 on 2026-07-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='conversation_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('tender', 'İhale'), ('info', 'Bilgi'), ('alarm', 'Alarm'), ('chat', 'Sohbet')], default='info', max_length=20),
        ),
    ]
