# Generated by Django 5.1.6 on 2026-07-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0002_notification_conversation_id_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedfilter',
            name='last_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenderalarm',
            name='completed_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenderalarm',
            name='last_dokuman_sayisi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenderalarm',
            name='last_ihale_durum',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
