# Generated by Django 5.1.6 on 2026-07-22 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0003_savedfilter_last_notified_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteAuthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detsis_no', models.CharField(db_index=True, max_length=64)),
                ('idare_id', models.CharField(blank=True, max_length=64, null=True)),
                ('ad', models.CharField(blank=True, max_length=500)),
                ('has_items', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_authorities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favori İdare',
                'verbose_name_plural': 'Favori İdareler',
                'ordering': ['-added_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'detsis_no'), name='uniq_user_favorite_authority')],
            },
        ),
    ]
