# Generated by Django 5.1.6 on 2026-07-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0004_favoriteauthority'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='filter_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
