# Generated by Django 5.1.6 on 2026-07-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0005_notification_filter_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteauthority',
            name='alarm',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='favoriteauthority',
            name='last_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='authority_detsis',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
