# Generated by Django 5.1.6 on 2026-07-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0006_favoriteauthority_alarm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='okas_kodlar',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
