# Generated by Django 5.1.6 on 2026-07-30 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0007_notification_okas_kodlar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tender_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'İhale Klasörü',
                'verbose_name_plural': 'İhale Klasörleri',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='savedtender',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenders', to='tenders.tendergroup'),
        ),
        migrations.AddConstraint(
            model_name='tendergroup',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='uniq_user_tender_group'),
        ),
    ]
