# Generated by Django 5.1.6 on 2026-08-04 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekap', '0012_contract_ilk_gorulme'),
        ('tenders', '0008_tendergroup_savedtender_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='contractor_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FavoriteContractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm', models.BooleanField(default=True)),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takip_edenler', to='ekap.contractor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_contractors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Takip Edilen Firma',
                'verbose_name_plural': 'Takip Edilen Firmalar',
                'ordering': ['-added_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'contractor'), name='uniq_user_favorite_contractor')],
            },
        ),
    ]
