# Generated by Django 5.1.6 on 2026-09-26 08:23

from django.db import migrations, models

# `Notification.ilan_gun` — filtre bildiriminin KAPSADIĞI yayım günü.
#
# ⚠️ Kolon **nullable**, bu yüzden 2026-08-28 arızası (3 gün veri kaybı) burada
# tekrarlanamaz: o arıza `NOT NULL` kolonlarda yaşanmıştı — eski worker'lar alanı
# INSERT'e hiç koymuyor, DB'de default olmadığı için satır düşüyordu. NULL kabul
# edilen bir kolonda eski kod sorunsuz yazmaya devam eder. Bu yüzden ayrıca
# DB seviyesinde default vermek gerekmiyor.


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0009_notification_contractor_id_favoritecontractor'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='ilan_gun',
            field=models.DateField(blank=True, null=True),
        ),
    ]
