# Generated by Django 5.1.6 on 2026-09-28 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0010_notification_ilan_gun'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='pencere_bas',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='pencere_bit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
