# Generated by Django 5.1.6 on 2026-09-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0011_notification_kayit_penceresi'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='filtre_idler',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='notification',
            name='idare_detsis_liste',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
