# Generated by Django 5.1.6 on 2026-07-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_expires_at',
            field=models.DateTimeField(blank=True, help_text="Boşsa süresiz Pro; doluysa bu tarihten sonra Free'ye düşer.", null=True, verbose_name='abonelik bitişi'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_tier',
            field=models.CharField(choices=[('free', 'Ücretsiz'), ('pro', 'Pro')], default='free', max_length=10, verbose_name='abonelik katmanı'),
        ),
    ]
