# Generated by Django 5.1.6 on 2026-08-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_subscription_expires_at_user_subscription_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_cancel_reason',
            field=models.CharField(blank=True, help_text='RevenueCat cancel_reason / expiration_reason (UNSUBSCRIBE, BILLING_ERROR, CUSTOMER_SUPPORT ...).', max_length=32, verbose_name='iptal nedeni'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_cancelled_at',
            field=models.DateTimeField(blank=True, help_text="RevenueCat CANCELLATION/EXPIRATION event'i geldiği an. Yeni satın alma / iptalden dönüş (UNCANCELLATION) ile temizlenir.", null=True, verbose_name='abonelik iptal tarihi'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_last_event',
            field=models.CharField(blank=True, help_text="RevenueCat'ten gelen son webhook event tipi (teşhis için).", max_length=40, verbose_name="son RC event'i"),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_period_type',
            field=models.CharField(blank=True, help_text="Son event'in dönem tipi: TRIAL (ücretsiz deneme), NORMAL, INTRO. Deneme iptali ile ücretli iptali ayırt eder.", max_length=16, verbose_name='dönem tipi'),
        ),
    ]
