# Generated by Django 5.1.6 on 2026-09-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_subscription_cancel_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Uygulamayı en son ne zaman kullandı (kimliği doğrulanan istek).', null=True, verbose_name='son görülme'),
        ),
    ]
