# Generated by Django 5.1.6 on 2026-09-14 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_onboarding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age_range',
        ),
        migrations.RemoveField(
            model_name='user',
            name='onboarding_completed_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='onboarding_status',
        ),
    ]
