# Generated by Django 5.1.6 on 2026-09-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_onboarding'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age_range',
            field=models.CharField(blank=True, choices=[('18_24', '18-24'), ('25_34', '25-34'), ('35_44', '35-44'), ('45_54', '45-54'), ('55_plus', '55+')], max_length=8, verbose_name='yaş aralığı'),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='sihirbaz tamamlanma'),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_status',
            field=models.CharField(choices=[('pending', 'Bekliyor'), ('skipped', 'Atlandı'), ('completed', 'Tamamlandı')], default='pending', max_length=10, verbose_name='tanışma sihirbazı'),
        ),
    ]
