# Generated by Django 5.1.6 on 2026-07-13 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ekap', '0003_tender_ozellikler_tender_yasa_kapsami'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=255)),
                ('sector', models.CharField(blank=True, max_length=255)),
                ('activity_areas', models.TextField(blank=True)),
                ('cities', models.JSONField(blank=True, default=list)),
                ('tender_types', models.JSONField(blank=True, default=list)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('past_works', models.JSONField(blank=True, default=list)),
                ('profile_map', models.JSONField(blank=True, null=True)),
                ('profile_map_generated_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Firma Profili',
                'verbose_name_plural': 'Firma Profilleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Kullanıcı'), ('assistant', 'Asistan')], max_length=10)),
                ('content', models.TextField()),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sohbet Mesajı',
                'verbose_name_plural': 'Sohbet Mesajları',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='assistant_c_user_id_4bfa13_idx')],
            },
        ),
        migrations.CreateModel(
            name='TenderRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('reasons', models.JSONField(default=list)),
                ('date', models.DateField(db_index=True)),
                ('seen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ekap.tender')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tender_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'İhale Önerisi',
                'verbose_name_plural': 'İhale Önerileri',
                'ordering': ['-score'],
                'constraints': [models.UniqueConstraint(fields=('user', 'tender'), name='uniq_user_tender_recommendation')],
            },
        ),
    ]
