# Generated by Django 5.1.6 on 2026-07-13 11:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_chatconversation_chatmessage_conversation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['conversation', '-created_at'], name='assistant_c_convers_1e4605_idx'),
        ),
    ]
