# Generated by Django 5.1.6 on 2026-07-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_chatmessage_assistant_c_convers_1e4605_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatconversation',
            name='tender_ikn',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
