# Generated by Django 5.1.6 on 2026-08-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0004_chatconversation_tender_ikn'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='profile_map_kaynak_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
