# Generated by Django 5.1.6 on 2026-08-25 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0005_companyprofile_profile_map_kaynak_hash'),
        ('ekap', '0019_okasitem_norm_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_profiles', to='ekap.contractor'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='il_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='website',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
