# Generated by Django 5.1.6 on 2026-08-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0006_companyprofile_contractor_companyprofile_il_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='usage',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
