# Generated by Django 5.1.6 on 2026-08-25 15:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0007_chatmessage_usage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tur', models.CharField(choices=[('ihale_kaydet', 'İhaleyi Kaydet'), ('alarm_kur', 'Alarm Kur'), ('filtre_kaydet', 'Filtre Kaydet')], max_length=20)),
                ('params', models.JSONField(default=dict)),
                ('ozet', models.CharField(max_length=250)),
                ('durum', models.CharField(choices=[('bekliyor', 'Bekliyor'), ('onaylandi', 'Onaylandı'), ('reddedildi', 'Reddedildi'), ('suresi_doldu', 'Süresi Doldu'), ('hata', 'Hata')], default='bekliyor', max_length=15)),
                ('sonuc', models.JSONField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='assistant.chatmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asistan Eylemi',
                'verbose_name_plural': 'Asistan Eylemleri',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'durum'], name='assistant_a_user_id_c2a5d9_idx')],
            },
        ),
    ]
