# Generated by Django 5.1.6 on 2026-08-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0008_assistantaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistantaction',
            name='tur',
            field=models.CharField(choices=[('ihale_kaydet', 'İhaleyi Kaydet'), ('alarm_kur', 'Alarm Kur'), ('filtre_kaydet', 'Filtre Kaydet'), ('toplu_ihale_kaydet', 'İhaleleri Toplu Kaydet'), ('ihale_tasi', 'İhaleyi Klasöre Taşı'), ('firma_takip', 'Firmayı Takibe Al'), ('idare_favori', 'İdareyi Favoriye Ekle'), ('kayit_sil', 'Kaydı Sil')], max_length=20),
        ),
    ]
