# Generated by Django 5.1.6 on 2026-08-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0009_alter_assistantaction_tur'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatconversation',
            name='son_arama',
            field=models.JSONField(blank=True, null=True, verbose_name='Son arama filtresi'),
        ),
    ]
