# Generated by Django 5.1.6 on 2026-08-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0010_chatconversation_son_arama'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='hitap',
            field=models.CharField(blank=True, choices=[('bey', 'Bey'), ('hanim', 'Hanım'), ('yok', 'Hitap kullanma')], max_length=8, verbose_name='Hitap'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='hitap_ad',
            field=models.CharField(blank=True, max_length=60, verbose_name='Hitap adı'),
        ),
    ]
