# Generated by Django 5.1.6 on 2026-07-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ikn', models.CharField(db_index=True, max_length=100, verbose_name='İKN')),
                ('analysis_type', models.CharField(choices=[('tech_spec', 'Teknik Şartname'), ('admin_spec', 'İdari Şartname'), ('cost_analysis', 'Maliyet Analizi'), ('generate_keywords', 'Anahtar Kelime')], max_length=30)),
                ('analysis', models.TextField()),
                ('usage', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Analiz (Cache)',
                'verbose_name_plural': 'AI Analizler (Cache)',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('ikn', 'analysis_type'), name='uniq_ikn_analysis_type')],
            },
        ),
    ]
